#!/bin/sh

status() { \
    # Module Storage
    storage="^b#d3869b^^c#000000^ 󰆼 ^b#b16286^^c#000000^$(df --human --output=avail /dev/mapper/cryptvg-root | sed -n '1!p') "
    
    # Module Network
    connection_type=$(ip route | awk '/default/ { gsub(/ /, "", $5); print substr($5,1,2); exit }')
    case $connection_type in
        en)
	    network="^b#b8bb26^^c#000000^ 󰈀 ^b#98971a^^c#000000^ UP ";;
	wl)
	    wlan=$(iwconfig wlan0 | grep -i quality | awk '{print $2}' | cut -d'=' -f2 | cut -d'/' -f1)
	    network="^b#b8bb26^^c#000000^ 󰖩 ^b#98971a^^c#000000^ $wlan% ";;
	ww)
	    wwan="98%"
	    network="^b#b8bb26^^c#000000^ 󰢾 ^b#98971a^^c#000000^ $wwan ";;	
    esac

    # Module Audio
    current_sink=$(pactl info | awk -F': ' '/Default Sink/ {split($2, a, "."); gsub(/^[ \t\n]+|[ \t\n]+$/, "", a[1]); print a[1]}')
    volume=$(pw-volume status | jq -r '.percentage' | cut -d. -f1)

    case $current_sink in
        alsa_output)
            # TODO: Add an if statement to see if its also using headphone jack:
            audio_type="speaker";;
        bluez_output)
            audio_type="bluetooth";;
    esac

    case $audio_type in
	bluetooth)
	    audio="^b#83a598^^c#000000^ 󰂯 ^b#458588^^c#000000^ $volume% ";;
	jack)
	    audio="^b#83a598^^c#000000^ 󱎔 ^b#458588^^c#000000^ $volume% ";;
    speaker)
	    audio="^b#83a598^^c#000000^ 󰓃 ^b#458588^^c#000000^ $volume% ";;
	*)
	    :;;
    esac

    # Module Battery
    battery_health=$(cat /sys/class/power_supply/BAT0/capacity)
    charging=$(cat /sys/class/power_supply/AC/online)
    case $battery_health in
	[0-9])
	    case $charging in
		0)
		    battery_glyph="󰂎";;
		1)
		    battery_glyph="󰢟";;
	    esac;;
	1[0-9])
	    case $charging in
		0)
		    battery_glyph="󰁺";;
		1)
		    battery_glyph="󰢜";;
	    esac;;
	2[0-9])
	    case $charging in
	        0)
		    battery_glyph="󰁻";;
		1)
		    battery_glyph="󰂆";;
	    esac;;
	3[0-9])
	    case $charging in
		0)
		    battery_glyph="󰁼";;
		1)
		    battery_glyph="󰂇";;
	    esac;;
	4[0-9])
	    case $charging in
		0)
		    battery_glyph="󰁽";;
		1)
		    battery_glyph="󰂈";;
	    esac;;
	5[0-9])
	    case $charging in
                0)
                    battery_glyph="󰁾";;
                1)
                    battery_glyph="󰢝";;
            esac;;
	6[0-9])
	    case $charging in
                0)
                    battery_glyph="󰁿";;
                1)
                    battery_glyph="󰂉";;
            esac;;
        7[0-9])
	    case $charging in
                0)
                    battery_glyph="󰂀";;
                1)
                    battery_glyph="󰢞";;
            esac;;
        8[0-9])
	    case $charging in
                0)
                    battery_glyph="󰂁";;
                1)
                    battery_glyph="󰂊";;
            esac;;
        9[0-9])
	    case $charging in
                0)
                    battery_glyph="󰂂";;
                1)
                    battery_glyph="󰂋";;
            esac;;
	100)
	    case $charging in
                0)
                    battery_glyph="󰁹";;
                1)
                    battery_glyph="󰂄";;
            esac;;
    esac 
    battery="^b#fabd2f^^c#000000^ $battery_glyph ^b#d79921^^c#000000^ $battery_health% " 

    # Module Time
    hhmm=$(date +'%I:%M')
    ampm=$(date +'%p' | tr '[:upper:]' '[:lower:]')
    time="^b#8ec07c^^c#000000^ 󰥔 ^b#689d6a^^c#000000^ $hhmm"

    # Statusline
    echo "$network^b#000000^ $battery^b#000000^ $audio^b#000000^ $storage^b#000000^ $time"
}

# Program Loop
while true
do
    xsetroot -name "$(status| tr '\n' ' ')"

    sleep 1m
done
