# Alacritty Configuration

# Window settings
[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 2, y = 2 }
decorations = "full"
startup_mode = "Windowed"

# Font configuration
[font]
normal = { family = "Comic Code", style = "Regular" } 
bold = { family = "Comic Code", style = "Bold" }
italic = { family = "Comic Code", style = "Italic" }
size = 26.0

# Colors (Dracula)
[colors.primary]
background = "#000000"
foreground = "#ebdbb2"

[colors.normal]
black = "#000000"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

# Cursor style
[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 750
unfocused_hollow = true

# Shell
[shell]
program = "/bin/fish"

# Key bindings
[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"
